import app from './index-v1.2.js';
const VERSION='1.3.0';
const enhancement=String.raw`<style>
.decision-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:10px;margin-top:10px}.decision-card{border:1px solid rgba(127,127,127,.25);border-radius:12px;padding:12px}.decision-card h3{margin:0 0 8px;font-size:16px}.decision-item{padding:8px 0;border-top:1px solid rgba(127,127,127,.18)}.decision-item:first-of-type{border-top:0}.decision-high{font-weight:700}.scenario-table{overflow-x:auto}.scenario-table table{width:100%;border-collapse:collapse;font-size:13px}.scenario-table th,.scenario-table td{padding:6px;border-bottom:1px solid rgba(127,127,127,.18);text-align:left;white-space:nowrap}.why-components{font-size:11px;opacity:.8}.decision-guard{margin-top:10px;font-size:12px;opacity:.8}
</style><script>
(()=>{
 const raceSection=document.getElementById('race');
 if(raceSection&&!document.getElementById('decisionLab'))raceSection.insertAdjacentHTML('beforeend','<div class="section-title">Decision LAB</div><div class="card" id="decisionLab"><div class="notice">哲平印と事前LOCK済みLABO予想を突き合わせ中…</div></div>');
 const val=v=>v==null?'—':v;
 function item(x,body,cls=''){return '<div class="decision-item '+cls+'"><b>'+x.horseNo+' '+esc(x.horseName||'')+'</b>'+body+'</div>'}
 function counterHtml(xs){if(!xs?.length)return '<div class="notice">強い反証アラートなし。</div>';return xs.map(x=>item(x,'<br><small>USER '+esc(x.userMark||'—')+' / LABO '+val(x.laboRank)+'位</small><br>'+esc((x.reasons||[]).join('・')),x.severity==='high'?'decision-high':'')).join('')}
 function missedHtml(xs){if(!xs?.length)return '<div class="notice">LABO上位の見逃し候補なし。</div>';return xs.map(x=>item(x,'<br><small>LABO '+val(x.laboRank)+'位 / '+val(x.laboScore)+'pt</small><br>'+esc(x.alert||''))).join('')}
 function scenarioHtml(xs){if(!xs?.length)return '<div class="notice">シナリオなし。</div>';const rows=xs.map(s=>{const top=(s.runners||[]).slice(0,5).map(r=>r.scenarioRank+'位 '+r.horseNo+' '+esc(r.horseName||'')+' ('+(r.scenarioDelta>=0?'+':'')+val(r.scenarioDelta)+')').join('<br>');return '<tr><td>'+esc(s.track)+'</td><td>'+esc(s.pace)+'</td><td>'+top+'</td></tr>'}).join('');return '<div class="scenario-table"><table><thead><tr><th>馬場</th><th>ペース</th><th>シナリオ上位5頭 / Δ</th></tr></thead><tbody>'+rows+'</tbody></table></div>'}
 function whyHtml(xs){if(!xs?.length)return '<div class="notice">WHYログなし。</div>';return xs.map(x=>{const c=x.components||{};const comp=Object.entries(c).map(([k,v])=>esc(k)+': '+esc(v)).join(' / ');return item(x,'<br><small>'+esc(x.why||'')+'</small>'+(comp?'<div class="why-components">'+comp+'</div>':''))}).join('')}
 function render(d){const box=document.getElementById('decisionLab');if(!box)return;const z=d.decisionLab;if(!z?.available){box.innerHTML='<div class="notice">Decision LAB待機中: '+esc(z?.reason||'事前LOCK予想がまだありません。')+'</div>';return}box.innerHTML='<div class="history-meta"><span class="pill ok">v'+esc(d.version||'')+'</span><span class="pill">USER rev '+esc(d.userRevision?.revisionNo??'—')+'</span><span class="pill">結果非参照</span></div><div class="decision-grid"><div class="decision-card"><h3>⚠️ 反証</h3>'+counterHtml(z.counterevidence)+'</div><div class="decision-card"><h3>👀 見逃し馬</h3>'+missedHtml(z.missedHorses)+'</div><div class="decision-card"><h3>🔀 IF 3×3</h3>'+scenarioHtml(z.scenarios)+'</div><div class="decision-card"><h3>🧠 WHY</h3>'+whyHtml(z.why)+'</div></div><div class="decision-guard">LOCK済み予想は変更しません。IFは感度分析のみ。結果リーク・自動ウェイト変更なし。</div>'}
 async function loadDecisionLab(){const box=document.getElementById('decisionLab');if(!box)return;const track=document.getElementById('track')?.value||'';try{const q='/v1/lab/decision-lab?date=2026-10-10&venue='+encodeURIComponent('東京')+'&race_no=11'+(track?'&track='+encodeURIComponent(track):'');render(await get(q))}catch(e){box.innerHTML='<div class="notice">Decision LAB: '+esc(e.message)+'</div>'}}
 const oldRefresh=window.refreshAll;window.refreshAll=async function(){await oldRefresh();await loadDecisionLab()};
 const oldLoadRace=window.loadRace;window.loadRace=async function(){await oldLoadRace();await loadDecisionLab()};
 setTimeout(loadDecisionLab,0);
})();
</script>`;
export default{async fetch(request,env,ctx){const u=new URL(request.url);if(u.pathname==='/health')return new Response(JSON.stringify({ok:true,service:'keiba-lab-app',version:VERSION,features:['history-browser','immutable-labo-prediction-marks','human-mark-audit','saudi-rc-gates','decision-lab-counterevidence','decision-lab-missed-horses','decision-lab-scenarios','decision-lab-why']}),{headers:{'content-type':'application/json; charset=UTF-8'}});const r=await app.fetch(request,env,ctx);if(!r.ok||!(r.headers.get('content-type')||'').includes('text/html'))return r;const body=await r.text();return new Response(body.replace('</body>',enhancement+'</body>'),{status:r.status,headers:r.headers})}};
