import app from './index-v1.9.js';
const VERSION='1.12.4';
export function mergeMainRaceTargets(input=[]){
 const original=Array.isArray(input)?input.filter(x=>x&&typeof x==='object'):[];
 const presets=[
  {date:'2026-10-10',venue:'東京',raceNo:11,raceName:'サウジアラビアロイヤルカップ',grade:'GIII'},
  {date:'2026-10-11',venue:'東京',raceNo:11,raceName:'アイルランドトロフィー',grade:'GII'}
 ];
 const out=original.slice();
 for(const preset of presets){
  if(!out.some(x=>x.date===preset.date&&x.venue===preset.venue&&Number(x.raceNo)===preset.raceNo))out.push({...preset,cardComplete:false,presetOnly:true});
 }
 return out;
}
const enhancement=String.raw`<script>(()=>{let target=null;window.getLaboTarget=()=>target;const race=document.getElementById('race');const mergeMainRaceTargets=${mergeMainRaceTargets.toString()};if(race&&!document.getElementById('genericOpsPanel'))race.insertAdjacentHTML('afterbegin','<div class="section-title">🎯 対象レース</div><div class="card" id="genericOpsPanel"><div class="row"><span>分析対象</span><span class="r"><select id="raceTarget"></select></span></div><div id="opsState" class="notice">開催プログラムを取得中…</div></div><div class="section-title">🚨 当日チェック</div><div class="card"><div id="raceAlertsBody" class="notice">対象レース選択後に自動点検します。</div></div>');let opsRequest=0;const q=()=>'?date='+encodeURIComponent(target.date)+'&venue='+encodeURIComponent(target.venue)+'&race_no='+target.raceNo;const label=x=>({WAIT_OFFICIAL_CARD:'公式出馬表待ち',FIX_CARD_AUDIT:'保存監査を修正',CREATE_PRELOCK:'LABO事前LOCK',ENTER_USER_MARKS:'哲平印を入力',RUN_DECISION_LAB:'DB再精査',READY_PRE_RACE:'事前準備OK',RESOLVE_BLOCKER:'BLOCK要因を解消'})[x]||x||'—';
function title(){return target?target.date+' '+target.venue+target.raceNo+'R '+(target.raceName||target.grade||''):''}
function renderAlerts(a={}){const b=document.getElementById('raceAlertsBody'),xs=a.alerts||[];if(!b)return;b.innerHTML='<div class="history-meta"><span class="pill">'+esc(a.status||'—')+'</span><span class="pill">警告 '+xs.length+'件</span></div>'+(xs.length?xs.map(x=>'<div class="row"><span>'+esc(String(x.severity||'').toUpperCase())+'</span><span class="r">'+esc(x.message||x.code||'')+'</span></div>').join(''):'<div class="notice">現在取得できる事前データでは追加警告なし。</div>')+'<div class="notice">オッズ・馬体重・リアルタイムトラックバイアスは未接続。未取得値は推測しません。</div>'}
async function loadOps(){if(!target)return;const seq=++opsRequest;window.dispatchEvent(new Event('labo-target-change'));const homeLabel=document.getElementById('gate')?.previousElementSibling;if(homeLabel)homeLabel.textContent=target.raceName||'対象レース';const heading=race?.querySelector('.section-title');if(heading&&heading.textContent.includes('東京11R'))heading.textContent=title();const s=document.getElementById('opsState'),track=document.getElementById('track')?.value||'';try{const d=await get('/v1/lab/race-ops'+q()+(track?'&track='+encodeURIComponent(track):'')),o=d.ops||{},p=d.prelock||{};if(seq!==opsRequest)return;s.innerHTML='<b>'+esc(title())+'</b><br>出馬表 '+(o.cardComplete?'✓':'待機')+' / 監査 '+esc(p.gate||'—')+' / LOCK '+(o.predictionReady?'✓':'待機')+' / USER印 '+(o.userMarkReady?'✓':'待機')+' / 再精査 '+(o.decisionReady?'✓':'待機')+'<br><b>次工程：'+esc(label(o.nextAction))+'</b>';const official=document.getElementById('official'),next=document.getElementById('nextGate'),gate=document.getElementById('gate'),opCard=document.getElementById('opCard');if(official)official.textContent=o.cardComplete?'完全保存':'未完了';const precard=document.getElementById('precard');if(precard)precard.textContent=o.cardComplete?'正式出馬表で照合':'正式出馬表で確認待ち';if(next)next.textContent=label(o.nextAction);if(gate)gate.textContent=label(o.nextAction);if(opCard)opCard.textContent=(d.readiness?.cardComplete?'完全保存':'確認中');const st=race?.querySelectorAll('.section-title');if(st)for(const el of st)if(/サウジアラビアRC|サウジアラビアロイヤルカップ|アイルランドT|アイルランドトロフィー/.test(el.textContent))el.textContent=title();renderAlerts(d.alerts||{})}catch(e){if(seq!==opsRequest)return;s.textContent='対象レース待機：'+e.message;renderAlerts({status:'WAIT',alerts:[]})}}
async function initTargets(){
 const selector=document.getElementById('raceTarget');
 if(!selector)return;
 let source=[],fetchError=null;
 try{const d=await get('/v1/lab/targets');source=d.races||[];}catch(e){fetchError=e;}
 const rs=mergeMainRaceTargets(source);
 selector.innerHTML=rs.map((x,i)=>'<option value="'+i+'">'+esc(x.date+' '+x.venue+x.raceNo+'R '+(x.raceName||x.grade||'')+(x.presetOnly?' · 保存確認待ち':x.cardComplete?' ✓':''))+'</option>').join('');
 if(!rs.length){selector.innerHTML='<option>対象待ち</option>';return;}
 async function choose(i){const next=rs[i];if(!next)return false;target=next;selector.value=String(i);await loadOps();return true;}
 window.selectLaboRace=(date,venue,raceNo)=>{const i=rs.findIndex(x=>x.date===date&&x.venue===venue&&Number(x.raceNo)===Number(raceNo));if(i<0)return false;void choose(i);return true;};
 selector.onchange=()=>{void choose(Number(selector.value));};
 let i=rs.findIndex(x=>x.date==='2026-10-11'&&x.venue==='東京'&&Number(x.raceNo)===11);
 if(i<0)i=0;
 if(fetchError){const state=document.getElementById('opsState');if(state)state.textContent='対象一覧APIの取得に失敗。登録済みレースを候補として表示し、選択後に個別照合します。';}
 await choose(i);
}
window.auditOfficialMarks=async function(){if(!target)return;const auditTarget=target,phase=document.getElementById('phase').value,track=document.getElementById('markTrack').value;const marks=[...document.querySelectorAll('.markrow')].map(r=>{const v=r.querySelector('.horse').value.trim(),mark=r.querySelector('.mk').value;if(!v)return null;return /^\d+$/.test(v)?{horseNo:Number(v),mark}:{horseName:v,mark}}).filter(Boolean);if(!marks.length){document.getElementById('auditResult').textContent='印を1頭以上入力してください。';return}const body={date:target.date,venue:target.venue,raceNo:target.raceNo,phase,marks};if(track)body.track=track;try{const r=await fetch(API+'/v1/lab/user-mark-audit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(target!==auditTarget||document.getElementById('phase').value!==phase)return;if(window.showLaboAudit)window.showLaboAudit(j,{inline:true});else document.getElementById('auditResult').textContent=JSON.stringify(j,null,2);await loadOps()}catch(e){document.getElementById('auditResult').textContent='監査失敗: '+e.message}};
document.getElementById('makeNoteDraft')?.addEventListener('click',async e=>{e.stopImmediatePropagation();e.preventDefault();if(!target)return;const t=document.getElementById('noteDraftText'),b=document.getElementById('makeNoteDraft'),c=document.getElementById('copyNoteDraft');b.disabled=true;t.value='完全版予想記事を生成中…';try{const track=document.getElementById('track')?.value||'',d=await get('/v1/lab/note-draft'+q()+(track?'&track='+encodeURIComponent(track):''));t.value=d.text||'';c.disabled=!t.value}catch(err){t.value='記事生成待機：'+err.message;c.disabled=true}finally{b.disabled=false}},true);
window.auditMarks=window.auditOfficialMarks;document.getElementById('track')?.addEventListener('change',loadOps);const oldRefresh=window.refreshAll;window.refreshAll=async function(){if(oldRefresh)await oldRefresh();await loadOps()};const oldRace=window.loadRace;window.loadRace=async function(){if(oldRace)await oldRace();await loadOps()};initTargets()})();</script>`;
export default{async fetch(request,env,ctx){const u=new URL(request.url);if(u.pathname==='/health')return new Response(JSON.stringify({ok:true,service:'keiba-lab-app',version:VERSION,features:['generic-race-ops','generic-race-selector','dynamic-user-mark-audit','dynamic-full-note-draft','dynamic-race-alerts','performance-dashboard']}),{headers:{'content-type':'application/json; charset=UTF-8'}});const r=await app.fetch(request,env,ctx);if(!r.ok||!(r.headers.get('content-type')||'').includes('text/html'))return r;const body=await r.text();return new Response(body.replace('</body>',enhancement+'</body>'),{status:r.status,headers:r.headers})}};

