import app from './index-v1.9.js';
const VERSION='1.12.0';
const enhancement=String.raw`<script>(()=>{let target=null;const race=document.getElementById('race');if(race&&!document.getElementById('genericOpsPanel'))race.insertAdjacentHTML('afterbegin','<div class="section-title">🎯 対象レース</div><div class="card" id="genericOpsPanel"><div class="row"><span>分析対象</span><span class="r"><select id="raceTarget"></select></span></div><div id="opsState" class="notice">開催プログラムを取得中…</div></div><div class="section-title">🚨 当日チェック</div><div class="card"><div id="raceAlertsBody" class="notice">対象レース選択後に自動点検します。</div></div>');const q=()=>'?date='+encodeURIComponent(target.date)+'&venue='+encodeURIComponent(target.venue)+'&race_no='+target.raceNo;const label=x=>({WAIT_OFFICIAL_CARD:'公式出馬表待ち',FIX_CARD_AUDIT:'保存監査を修正',CREATE_PRELOCK:'LABO事前LOCK',ENTER_USER_MARKS:'哲平印を入力',RUN_DECISION_LAB:'DB再精査',READY_PRE_RACE:'事前準備OK',RESOLVE_BLOCKER:'BLOCK要因を解消'})[x]||x||'—';
function title(){return target?target.date+' '+target.venue+target.raceNo+'R '+(target.raceName||target.grade||''):''}
function renderAlerts(a={}){const b=document.getElementById('raceAlertsBody'),xs=a.alerts||[];if(!b)return;b.innerHTML='<div class="history-meta"><span class="pill">'+esc(a.status||'—')+'</span><span class="pill">警告 '+xs.length+'件</span></div>'+(xs.length?xs.map(x=>'<div class="row"><span>'+esc(String(x.severity||'').toUpperCase())+'</span><span class="r">'+esc(x.message||x.code||'')+'</span></div>').join(''):'<div class="notice">現在取得できる事前データでは追加警告なし。</div>')+'<div class="notice">オッズ・馬体重・リアルタイムトラックバイアスは未接続。未取得値は推測しません。</div>'}
async function loadOps(){if(!target)return;const s=document.getElementById('opsState'),track=document.getElementById('track')?.value||'';try{const d=await get('/v1/lab/race-ops'+q()+(track?'&track='+encodeURIComponent(track):'')),o=d.ops||{},p=d.prelock||{};s.innerHTML='<b>'+esc(title())+'</b><br>出馬表 '+(o.cardComplete?'✓':'待機')+' / 監査 '+esc(p.gate||'—')+' / LOCK '+(o.predictionReady?'✓':'待機')+' / USER印 '+(o.userMarkReady?'✓':'待機')+' / 再精査 '+(o.decisionReady?'✓':'待機')+'<br><b>次工程：'+esc(label(o.nextAction))+'</b>';const official=document.getElementById('official'),next=document.getElementById('nextGate'),gate=document.getElementById('gate'),opCard=document.getElementById('opCard');if(official)official.textContent=o.cardComplete?'完全保存':'未完了';if(next)next.textContent=label(o.nextAction);if(gate)gate.textContent=label(o.nextAction);if(opCard)opCard.textContent=(d.readiness?.cardComplete?'完全保存':'確認中');const st=race?.querySelectorAll('.section-title');if(st)for(const el of st)if(/サウジアラビアRC/.test(el.textContent))el.textContent=title();renderAlerts(d.alerts||{})}catch(e){s.textContent='対象レース待機：'+e.message;renderAlerts({status:'WAIT',alerts:[]})}}
async function initTargets(){const s=document.getElementById('raceTarget');try{const d=await get('/v1/lab/targets'),rs=d.races||[];s.innerHTML=rs.map((x,i)=>'<option value="'+i+'">'+esc(x.date+' '+x.venue+x.raceNo+'R '+(x.raceName||x.grade||'')+(x.cardComplete?' ✓':''))+'</option>').join('');if(!rs.length){s.innerHTML='<option>対象待ち</option>';return}let i=rs.findIndex(x=>x.date==='2026-10-10'&&x.venue==='東京'&&x.raceNo===11);if(i<0)i=rs.findIndex(x=>x.grade);if(i<0)i=0;s.value=String(i);target=rs[i];s.onchange=async()=>{target=rs[Number(s.value)]||null;await loadOps()};await loadOps()}catch(e){s.innerHTML='<option>取得待機</option>';document.getElementById('opsState').textContent=e.message}}
window.auditMarks=async function(){if(!target)return;const phase=document.getElementById('phase').value,track=document.getElementById('markTrack').value;const marks=[...document.querySelectorAll('.markrow')].map(r=>{const v=r.querySelector('.horse').value.trim(),mark=r.querySelector('.mk').value;if(!v)return null;return /^\\d+$/.test(v)?{horseNo:Number(v),mark}:{horseName:v,mark}}).filter(Boolean);if(!marks.length){document.getElementById('auditResult').textContent='印を1頭以上入力してください。';return}const body={date:target.date,venue:target.venue,raceNo:target.raceNo,phase,marks};if(track)body.track=track;try{const r=await fetch(API+'/v1/lab/user-mark-audit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),j=await r.json();document.getElementById('auditResult').textContent=JSON.stringify(j,null,2);await loadOps()}catch(e){document.getElementById('auditResult').textContent='監査失敗: '+e.message}};
document.getElementById('makeNoteDraft')?.addEventListener('click',async e=>{e.stopImmediatePropagation();e.preventDefault();if(!target)return;const t=document.getElementById('noteDraftText'),b=document.getElementById('makeNoteDraft'),c=document.getElementById('copyNoteDraft');b.disabled=true;t.value='完全版予想記事を生成中…';try{const track=document.getElementById('track')?.value||'',d=await get('/v1/lab/note-draft'+q()+(track?'&track='+encodeURIComponent(track):''));t.value=d.text||'';c.disabled=!t.value}catch(err){t.value='記事生成待機：'+err.message;c.disabled=true}finally{b.disabled=false}},true);
document.getElementById('track')?.addEventListener('change',loadOps);const oldRefresh=window.refreshAll;window.refreshAll=async function(){if(oldRefresh)await oldRefresh();await loadOps()};const oldRace=window.loadRace;window.loadRace=async function(){if(oldRace)await oldRace();await loadOps()};initTargets()})();</script>`;
export default{async fetch(request,env,ctx){const u=new URL(request.url);if(u.pathname==='/health')return new Response(JSON.stringify({ok:true,service:'keiba-lab-app',version:VERSION,features:['generic-race-ops','generic-race-selector','dynamic-user-mark-audit','dynamic-full-note-draft','dynamic-race-alerts','performance-dashboard']}),{headers:{'content-type':'application/json; charset=UTF-8'}});const r=await app.fetch(request,env,ctx);if(!r.ok||!(r.headers.get('content-type')||'').includes('text/html'))return r;const body=await r.text();return new Response(body.replace('</body>',enhancement+'</body>'),{status:r.status,headers:r.headers})}};
